const mongoose = require('mongoose');

const materialSchema = new mongoose.Schema({
  originalName: {
    type: String,
    required: true,
    trim: true,
  },
  filename: {
    type: String,
    required: true,
    unique: true,
  },
  filePath: {
    type: String,
    required: true,
  },
  subject: {
    type: String,
    required: true,
    enum: ['python', 'java', 'cpp', 'c', 'mixed'],
  },
  status: {
    type: String,
    enum: ['processing', 'completed', 'failed'],
    default: 'processing',
  },
  uploadedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  // --- ADD THIS FIELD ---
  // This will store the array of quiz questions generated by the AI
  quiz_content: {
    type: Array, 
    default: []
  },
  // --- END OF ADDITION ---
  completed_at: {
    type: Date,
  },
  failed_at: {
    type: Date,
  },
  error: {
    type: String,
  }
});

module.exports = mongoose.model('Material', materialSchema);